// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VantaiViet.CoreApi.Data;

#nullable disable

namespace VantaiViet.CoreApi.Data.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    [Migration("20260918131317_AddOtpDeliveryQueue")]
    partial class AddOtpDeliveryQueue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("Roles_NormalizedName_key");

                    b.ToTable("Roles", "public");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "public");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "public");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "public");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "public");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "public");
                });

            modelBuilder.Entity("VantaiViet.CoreApi.Entities.AuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ActorReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TraceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId", "OccurredAt")
                        .HasDatabaseName("IX_Audit_Actor");

                    b.HasIndex("TargetType", "TargetId", "OccurredAt")
                        .HasDatabaseName("IX_Audit_Target");

                    b.ToTable("AuditEvents", "public", t =>
                        {
                            t.HasCheckConstraint("CK_AuditEvents_1", "\"Outcome\" IN ('Succeeded','Failed','Denied')");
                        });
                });

            modelBuilder.Entity("VantaiViet.CoreApi.Entities.AuthSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FamilyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<byte[]>("RefreshTokenHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("IX_AuthSessions_Family");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique()
                        .HasDatabaseName("AuthSessions_RefreshTokenHash_key");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_AuthSessions_User");

                    b.ToTable("AuthSessions", "public", t =>
                        {
                            t.HasCheckConstraint("CK_AuthSessions_1", "octet_length(\"RefreshTokenHash\") = 32");

                            t.HasCheckConstraint("CK_AuthSessions_2", "\"ExpiresAt\" > \"CreatedAt\"");
                        });
                });

            modelBuilder.Entity("VantaiViet.CoreApi.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DriverUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Confirmed");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DriverUserId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.HasIndex("ShipmentId")
                        .IsUnique();

                    b.HasIndex("VehicleId");

                    b.ToTable("Bookings", "public", t =>
                        {
                            t.HasCheckConstraint("CK_Bookings_Status", "\"Status\" IN ('Confirmed','Completed','Cancelled')");
                        });
                });

            modelBuilder.Entity("VantaiViet.CoreApi.Entities.DriverProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LicenseClass")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly>("LicenseExpiresOn")
                        .HasColumnType("date");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Submitted");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.HasKey("UserId");

                    b.HasIndex("ReviewerUserId");

                    b.ToTable("DriverProfiles", "public", t =>
                        {
                            t.HasCheckConstraint("CK_DriverProfiles_Status", "\"Status\" IN ('Submitted','Approved','Rejected')");

                            t.HasCheckConstraint("CK_DriverProfiles_Version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("VantaiViet.CoreApi.Entities.KycApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("RegistrationApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectionCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewerReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ReviewerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Draft");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.HasKey("Id");

                    b.HasIndex("RegistrationApplicationId")
                        .IsUnique()
                        .HasDatabaseName("UX_Kyc_ActiveApplication")
                        .HasFilter("\"Status\" IN ('Draft','Submitted','UnderReview','Approved')");

                    b.HasIndex("ReviewerUserId")
                        .HasDatabaseName("IX_Kyc_Reviewer");

                    b.HasIndex("Status", "SubmittedAt", "Id")
                        .HasDatabaseName("IX_Kyc_ReviewQueue");

                    b.ToTable("KycApplications", "public", t =>
                        {
                            t.HasCheckConstraint("CK_KycApplications_1", "\"Status\" IN ('Draft','Submitted','UnderReview','Approved','Rejected')");

                            t.HasCheckConstraint("CK_KycApplications_2", "\"Status\" = 'Draft' OR \"SubmittedAt\" IS NOT NULL");

                            t.HasCheckConstraint("CK_KycApplications_3", "\"Status\" NOT IN ('Approved','Rejected') OR (\"ReviewedAt\" IS NOT NULL AND \"ReviewerReference\" IS NOT NULL AND length(btrim(\"ReviewerReference\")) > 0)");

                            t.HasCheckConstraint("CK_KycApplications_4", "\"Status\" <> 'Rejected' OR (\"RejectionCode\" IS NOT NULL AND length(btrim(\"RejectionCode\")) > 0)");

                            t.HasCheckConstraint("CK_KycApplications_5", "\"ReviewedAt\" IS NULL OR (\"SubmittedAt\" IS NOT NULL AND \"ReviewedAt\" >= \"SubmittedAt\")");

                            t.HasCheckConstraint("CK_KycApplications_6", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("VantaiViet.CoreApi.Entities.KycDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("DeleteAfter")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("KycDocuments_StorageKey_key");

                    b.HasIndex("ApplicationId", "DocumentType")
                        .IsUnique()
                        .HasDatabaseName("KycDocuments_ApplicationId_DocumentType_key");

                    b.ToTable("KycDocuments", "public", t =>
                        {
                            t.HasCheckConstraint("CK_KycDocuments_1", "\"DocumentType\" IN ('IdentityFront','IdentityBack','Selfie')");

                            t.HasCheckConstraint("CK_KycDocuments_2", "length(btrim(\"StorageKey\")) > 0");

                            t.HasCheckConstraint("CK_KycDocuments_3", "\"SizeBytes\" > 0");

                            t.HasCheckConstraint("CK_KycDocuments_4", "\"DeleteAfter\" IS NULL OR \"DeleteAfter\" > \"UploadedAt\"");

                            t.HasCheckConstraint("CK_KycDocuments_5", "\"DeletedAt\" IS NULL OR \"DeletedAt\" >= \"UploadedAt\"");
                        });
                });

            modelBuilder.Entity("VantaiViet.CoreApi.Entities.KycIdentityDetail", b =>
                {
                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("EncryptionKeyId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly?>("ExpiresOn")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("HmacKeyId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte[]>("IdentityNumberEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("IdentityNumberHmac")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateOnly?>("IssuedOn")
                        .HasColumnType("date");

                    b.HasKey("ApplicationId");

                    b.HasIndex("HmacKeyId", "IdentityNumberHmac")
                        .HasDatabaseName("IX_KycIdentity_IdentityNumber");

                    b.ToTable("KycIdentityDetails", "public", t =>
                        {
                            t.HasCheckConstraint("CK_KycIdentityDetails_1", "length(btrim(\"FullName\")) > 0");

                            t.HasCheckConstraint("CK_KycIdentityDetails_2", "octet_length(\"IdentityNumberEncrypted\") > 0");

                            t.HasCheckConstraint("CK_KycIdentityDetails_3", "octet_length(\"IdentityNumberHmac\") = 32");

                            t.HasCheckConstraint("CK_KycIdentityDetails_4", "\"IssuedOn\" IS NULL OR \"IssuedOn\" >= \"DateOfBirth\"");

                            t.HasCheckConstraint("CK_KycIdentityDetails_5", "\"ExpiresOn\" IS NULL OR \"IssuedOn\" IS NULL OR \"ExpiresOn\" >= \"IssuedOn\"");
                        });
                });

            modelBuilder.Entity("VantaiViet.CoreApi.Entities.OtpDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProtectedCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RequestKey")
                        .HasColumnType("uuid");

                    b.Property<int>("SendAttempts")
                        .HasColumnType("integer");

                    b.Property<bool>("Simulated")
                        .HasColumnType("boolean");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("VerifyAttempts")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("LastAttemptAt");

                    b.HasIndex("Destination", "CreatedAt");

                    b.HasIndex("State", "NextAttemptAt");

                    b.HasIndex("UserId", "CreatedAt");

                    b.HasIndex("UserId", "RequestKey")
                        .IsUnique();

                    b.ToTable("OtpDeliveries", "public", t =>
                        {
                            t.HasCheckConstraint("CK_OtpDelivery_Attempts", "\"SendAttempts\" BETWEEN 0 AND 3 AND \"VerifyAttempts\" BETWEEN 0 AND 5");

                            t.HasCheckConstraint("CK_OtpDelivery_Channel", "\"Channel\" IN ('Email','Phone')");
                        });
                });

            modelBuilder.Entity("VantaiViet.CoreApi.Entities.RegistrationApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("PhoneVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("InProgress");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Registration_ActivePhone")
                        .HasFilter("\"Status\" = 'InProgress'");

                    b.ToTable("RegistrationApplications", "public", t =>
                        {
                            t.HasCheckConstraint("CK_RegistrationApplications_1", "\"PhoneNumber\" ~ '^\\+[1-9][0-9]{7,14}$'");

                            t.HasCheckConstraint("CK_RegistrationApplications_2", "\"Status\" IN ('InProgress','Completed','Expired','Cancelled')");

                            t.HasCheckConstraint("CK_RegistrationApplications_3", "\"ExpiresAt\" > \"CreatedAt\"");

                            t.HasCheckConstraint("CK_RegistrationApplications_4", "(\"Status\" = 'Completed') = (\"CompletedAt\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("VantaiViet.CoreApi.Entities.RegistrationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RegistrationApplicationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationApplicationId")
                        .HasDatabaseName("IX_RegistrationSessions_Application");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("RegistrationSessions_TokenHash_key");

                    b.ToTable("RegistrationSessions", "public", t =>
                        {
                            t.HasCheckConstraint("CK_RegistrationSessions_1", "octet_length(\"TokenHash\") = 32");

                            t.HasCheckConstraint("CK_RegistrationSessions_2", "\"ExpiresAt\" > \"CreatedAt\"");
                        });
                });

            modelBuilder.Entity("VantaiViet.CoreApi.Entities.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double?>("DeliveryLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("DeliveryLongitude")
                        .HasColumnType("double precision");

                    b.Property<string>("ExternalCustomerName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ExternalCustomerPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsExternalOrder")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PickupAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("PickupAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("PickupLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("PickupLongitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "CreatedAt");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("Shipments", "public", t =>
                        {
                            t.HasCheckConstraint("CK_Shipment_Status", "\"Status\" IN ('Draft','Published','Cancelled','Booked','Completed')");

                            t.HasCheckConstraint("CK_Shipment_Weight", "\"WeightKg\" > 0");
                        });
                });

            modelBuilder.Entity("VantaiViet.CoreApi.Entities.TransportRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DriverUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DriverUserId");

                    b.HasIndex("VehicleId");

                    b.HasIndex("ShipmentId", "DriverUserId")
                        .IsUnique();

                    b.ToTable("TransportRequests", "public", t =>
                        {
                            t.HasCheckConstraint("CK_TransportRequests_Status", "\"Status\" IN ('Pending','Accepted','Rejected','Withdrawn')");
                        });
                });

            modelBuilder.Entity("VantaiViet.CoreApi.Entities.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DriverUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PickedUpAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("DriverUserId")
                        .IsUnique()
                        .HasFilter("\"Status\" IN ('Assigned','InProgress','Loaded','Delivered')");

                    b.HasIndex("VehicleId")
                        .IsUnique()
                        .HasFilter("\"Status\" IN ('Assigned','InProgress','Loaded','Delivered')");

                    b.ToTable("Trips", "public", t =>
                        {
                            t.HasCheckConstraint("CK_Trips_Status", "\"Status\" IN ('Assigned','InProgress','Loaded','Delivered','Completed','Cancelled')");
                        });
                });

            modelBuilder.Entity("VantaiViet.CoreApi.Entities.TripEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProofId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("ProofId");

                    b.HasIndex("TripId", "OccurredAt");

                    b.ToTable("TripEvents", "public");
                });

            modelBuilder.Entity("VantaiViet.CoreApi.Entities.TripLocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("AccuracyMeters")
                        .HasColumnType("double precision");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<Guid>("PointId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Simulated")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TripId", "Id");

                    b.HasIndex("TripId", "PointId")
                        .IsUnique();

                    b.HasIndex("TripId", "RecordedAt", "Id");

                    b.ToTable("TripLocations", "public", t =>
                        {
                            t.HasCheckConstraint("CK_TripLocation_Accuracy", "\"AccuracyMeters\" BETWEEN 0 AND 1000");

                            t.HasCheckConstraint("CK_TripLocation_Coordinates", "\"Latitude\" BETWEEN -90 AND 90 AND \"Longitude\" BETWEEN -180 AND 180");
                        });
                });

            modelBuilder.Entity("VantaiViet.CoreApi.Entities.TripParticipant", b =>
                {
                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GrantedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("TripId", "UserId");

                    b.HasIndex("GrantedByUserId");

                    b.HasIndex("UserId");

                    b.ToTable("TripParticipants", "public");
                });

            modelBuilder.Entity("VantaiViet.CoreApi.Entities.TripProof", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UploaderUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.HasIndex("UploaderUserId");

                    b.ToTable("TripProofs", "public", t =>
                        {
                            t.HasCheckConstraint("CK_TripProof_Size", "octet_length(\"Content\") BETWEEN 8 AND 5242880");

                            t.HasCheckConstraint("CK_TripProof_Type", "\"ContentType\" IN ('image/jpeg','image/png')");
                        });
                });

            modelBuilder.Entity("VantaiViet.CoreApi.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AccessFailedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Active");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("LockoutEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("RegistrationApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_NormalizedEmail")
                        .HasFilter("\"NormalizedEmail\" IS NOT NULL");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_NormalizedUserName");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("Users_PhoneNumber_key");

                    b.HasIndex("RegistrationApplicationId")
                        .IsUnique()
                        .HasDatabaseName("Users_RegistrationApplicationId_key");

                    b.ToTable("Users", "public", t =>
                        {
                            t.HasCheckConstraint("CK_Users_Failures", "\"AccessFailedCount\" >= 0");

                            t.HasCheckConstraint("CK_Users_Name", "length(btrim(\"DisplayName\")) > 0");

                            t.HasCheckConstraint("CK_Users_Password", "length(btrim(\"PasswordHash\")) > 0");

                            t.HasCheckConstraint("CK_Users_Phone", "\"PhoneNumber\" ~ '^\\+[1-9][0-9]{7,14}$'");

                            t.HasCheckConstraint("CK_Users_Status", "\"AccountStatus\" IN ('Active','PendingKyc','Suspended','Disabled')");
                        });
                });

            modelBuilder.Entity("VantaiViet.CoreApi.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("DriverUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("MaxPayloadKg")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Submitted");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.HasKey("Id");

                    b.HasIndex("DriverUserId");

                    b.HasIndex("LicensePlate")
                        .IsUnique();

                    b.HasIndex("ReviewerUserId");

                    b.ToTable("Vehicles", "public", t =>
                        {
                            t.HasCheckConstraint("CK_Vehicles_Payload", "\"MaxPayloadKg\" > 0");

                            t.HasCheckConstraint("CK_Vehicles_Status", "\"Status\" IN ('Submitted','Approved','Rejected')");

                            t.HasCheckConstraint("CK_Vehicles_Version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("VantaiViet.CoreApi.Entities.VerificationChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<byte[]>("CodeHmac")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HmacKeyId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("MaxAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5);

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("RegistrationApplicationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationApplicationId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Challenges_Registration");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Challenges_User");

                    b.ToTable("VerificationChallenges", "public", t =>
                        {
                            t.HasCheckConstraint("CK_VerificationChallenges_1", "(\"RegistrationApplicationId\" IS NOT NULL) <> (\"UserId\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_VerificationChallenges_2", "(\"RegistrationApplicationId\" IS NOT NULL AND \"Purpose\" = 'RegistrationPhone') OR (\"UserId\" IS NOT NULL AND \"Purpose\" IN ('PasswordReset','VerifyEmail'))");

                            t.HasCheckConstraint("CK_VerificationChallenges_3", "octet_length(\"CodeHmac\") = 32");

                            t.HasCheckConstraint("CK_VerificationChallenges_4", "\"MaxAttempts\" > 0 AND \"AttemptCount\" BETWEEN 0 AND \"MaxAttempts\"");

                            t.HasCheckConstraint("CK_VerificationChallenges_5", "\"ExpiresAt\" > \"CreatedAt\"");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("VantaiViet.CoreApi.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("VantaiViet.CoreApi.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VantaiViet.CoreApi.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("VantaiViet.CoreApi.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("VantaiViet.CoreApi.Entities.AuditEvent", b =>
                {
                    b.HasOne("VantaiViet.CoreApi.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("VantaiViet.CoreApi.Entities.AuthSession", b =>
                {
                    b.HasOne("VantaiViet.CoreApi.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("VantaiViet.CoreApi.Entities.Booking", b =>
                {
                    b.HasOne("VantaiViet.CoreApi.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("DriverUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VantaiViet.CoreApi.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VantaiViet.CoreApi.Entities.TransportRequest", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VantaiViet.CoreApi.Entities.Shipment", null)
                        .WithMany()
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VantaiViet.CoreApi.Entities.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("VantaiViet.CoreApi.Entities.DriverProfile", b =>
                {
                    b.HasOne("VantaiViet.CoreApi.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ReviewerUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("VantaiViet.CoreApi.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("VantaiViet.CoreApi.Entities.KycApplication", b =>
                {
                    b.HasOne("VantaiViet.CoreApi.Entities.RegistrationApplication", null)
                        .WithMany()
                        .HasForeignKey("RegistrationApplicationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VantaiViet.CoreApi.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ReviewerUserId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("VantaiViet.CoreApi.Entities.KycDocument", b =>
                {
                    b.HasOne("VantaiViet.CoreApi.Entities.KycApplication", null)
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("VantaiViet.CoreApi.Entities.KycIdentityDetail", b =>
                {
                    b.HasOne("VantaiViet.CoreApi.Entities.KycApplication", null)
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("VantaiViet.CoreApi.Entities.OtpDelivery", b =>
                {
                    b.HasOne("VantaiViet.CoreApi.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("VantaiViet.CoreApi.Entities.RegistrationSession", b =>
                {
                    b.HasOne("VantaiViet.CoreApi.Entities.RegistrationApplication", null)
                        .WithMany()
                        .HasForeignKey("RegistrationApplicationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("VantaiViet.CoreApi.Entities.Shipment", b =>
                {
                    b.HasOne("VantaiViet.CoreApi.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("VantaiViet.CoreApi.Entities.TransportRequest", b =>
                {
                    b.HasOne("VantaiViet.CoreApi.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("DriverUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VantaiViet.CoreApi.Entities.Shipment", null)
                        .WithMany()
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VantaiViet.CoreApi.Entities.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("VantaiViet.CoreApi.Entities.Trip", b =>
                {
                    b.HasOne("VantaiViet.CoreApi.Entities.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VantaiViet.CoreApi.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("DriverUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VantaiViet.CoreApi.Entities.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("VantaiViet.CoreApi.Entities.TripEvent", b =>
                {
                    b.HasOne("VantaiViet.CoreApi.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VantaiViet.CoreApi.Entities.TripProof", null)
                        .WithMany()
                        .HasForeignKey("ProofId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("VantaiViet.CoreApi.Entities.Trip", null)
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("VantaiViet.CoreApi.Entities.TripLocation", b =>
                {
                    b.HasOne("VantaiViet.CoreApi.Entities.Trip", null)
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("VantaiViet.CoreApi.Entities.TripParticipant", b =>
                {
                    b.HasOne("VantaiViet.CoreApi.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("GrantedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VantaiViet.CoreApi.Entities.Trip", null)
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VantaiViet.CoreApi.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("VantaiViet.CoreApi.Entities.TripProof", b =>
                {
                    b.HasOne("VantaiViet.CoreApi.Entities.Trip", null)
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VantaiViet.CoreApi.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UploaderUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("VantaiViet.CoreApi.Entities.User", b =>
                {
                    b.HasOne("VantaiViet.CoreApi.Entities.RegistrationApplication", null)
                        .WithMany()
                        .HasForeignKey("RegistrationApplicationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("VantaiViet.CoreApi.Entities.Vehicle", b =>
                {
                    b.HasOne("VantaiViet.CoreApi.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("DriverUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VantaiViet.CoreApi.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ReviewerUserId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("VantaiViet.CoreApi.Entities.VerificationChallenge", b =>
                {
                    b.HasOne("VantaiViet.CoreApi.Entities.RegistrationApplication", null)
                        .WithMany()
                        .HasForeignKey("RegistrationApplicationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("VantaiViet.CoreApi.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);
                });
#pragma warning restore 612, 618
        }
    }
}
