-- One-time adoption of the existing public schema. Does not recreate user tables.
-- Validates schema, normalizes constraint/index names and installs trigger functions.
-- Any mismatch aborts the transaction. Run the ENTIRE script on the intended database.
BEGIN;
SET LOCAL lock_timeout = '5s';
SELECT pg_advisory_xact_lock(184732910);
CREATE TABLE IF NOT EXISTS public."__EFMigrationsHistory" (
    "MigrationId" VARCHAR(150) PRIMARY KEY,
    "ProductVersion" VARCHAR(32) NOT NULL
);
DO $guard$
BEGIN
    IF EXISTS (SELECT 1 FROM public."__EFMigrationsHistory") THEN
        RAISE EXCEPTION 'Migration history is not empty; baseline is a one-time operation';
    END IF;
END;
$guard$;
-- CREATE without IF NOT EXISTS ensures an existing schema is never removed.
CREATE SCHEMA _identity_kyc_reference;
CREATE TABLE _identity_kyc_reference."RegistrationApplications" (
    "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "PhoneNumber" character varying(20) NOT NULL,
    "PhoneVerifiedAt" timestamp with time zone,
    "DisplayName" character varying(150),
    "Status" character varying(20) NOT NULL DEFAULT 'InProgress',
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "ExpiresAt" timestamp with time zone NOT NULL,
    "CompletedAt" timestamp with time zone,
    CONSTRAINT "PK_RegistrationApplications" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_RegistrationApplications_1" CHECK ("PhoneNumber" ~ '^\+[1-9][0-9]{7,14}$'),
    CONSTRAINT "CK_RegistrationApplications_2" CHECK ("Status" IN ('InProgress','Completed','Expired','Cancelled')),
    CONSTRAINT "CK_RegistrationApplications_3" CHECK ("ExpiresAt" > "CreatedAt"),
    CONSTRAINT "CK_RegistrationApplications_4" CHECK (("Status" = 'Completed') = ("CompletedAt" IS NOT NULL))
);

CREATE TABLE _identity_kyc_reference."Roles" (
    "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "Name" character varying(256) NOT NULL,
    "NormalizedName" character varying(256) NOT NULL,
    "ConcurrencyStamp" text NOT NULL,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

CREATE TABLE _identity_kyc_reference."RegistrationSessions" (
    "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "RegistrationApplicationId" uuid NOT NULL,
    "TokenHash" bytea NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "ExpiresAt" timestamp with time zone NOT NULL,
    "RevokedAt" timestamp with time zone,
    CONSTRAINT "PK_RegistrationSessions" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_RegistrationSessions_1" CHECK (octet_length("TokenHash") = 32),
    CONSTRAINT "CK_RegistrationSessions_2" CHECK ("ExpiresAt" > "CreatedAt"),
    CONSTRAINT "FK_RegistrationSessions_RegistrationApplications_RegistrationA~" FOREIGN KEY ("RegistrationApplicationId") REFERENCES _identity_kyc_reference."RegistrationApplications" ("Id")
);

CREATE TABLE _identity_kyc_reference."Users" (
    "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "RegistrationApplicationId" uuid NOT NULL,
    "DisplayName" character varying(150) NOT NULL,
    "AccountStatus" character varying(20) NOT NULL DEFAULT 'Active',
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UserName" character varying(256) NOT NULL,
    "NormalizedUserName" character varying(256) NOT NULL,
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL DEFAULT FALSE,
    "PasswordHash" text NOT NULL,
    "SecurityStamp" text NOT NULL,
    "ConcurrencyStamp" text NOT NULL,
    "PhoneNumber" character varying(20) NOT NULL,
    "PhoneNumberConfirmed" boolean NOT NULL DEFAULT TRUE,
    "TwoFactorEnabled" boolean NOT NULL DEFAULT FALSE,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL DEFAULT TRUE,
    "AccessFailedCount" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_Users_Failures" CHECK ("AccessFailedCount" >= 0),
    CONSTRAINT "CK_Users_Name" CHECK (length(btrim("DisplayName")) > 0),
    CONSTRAINT "CK_Users_Password" CHECK (length(btrim("PasswordHash")) > 0),
    CONSTRAINT "CK_Users_Phone" CHECK ("PhoneNumber" ~ '^\+[1-9][0-9]{7,14}$'),
    CONSTRAINT "CK_Users_Status" CHECK ("AccountStatus" IN ('Active','Suspended','Disabled')),
    CONSTRAINT "FK_Users_RegistrationApplications_RegistrationApplicationId" FOREIGN KEY ("RegistrationApplicationId") REFERENCES _identity_kyc_reference."RegistrationApplications" ("Id")
);

CREATE TABLE _identity_kyc_reference."RoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_RoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RoleClaims_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES _identity_kyc_reference."Roles" ("Id")
);

CREATE TABLE _identity_kyc_reference."AuditEvents" (
    "Id" bigint GENERATED ALWAYS AS IDENTITY,
    "ActorUserId" uuid,
    "ActorReference" character varying(200),
    "Action" character varying(100) NOT NULL,
    "TargetType" character varying(100) NOT NULL,
    "TargetId" uuid NOT NULL,
    "Outcome" character varying(20) NOT NULL,
    "TraceId" character varying(100),
    "OccurredAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_AuditEvents" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_AuditEvents_1" CHECK ("Outcome" IN ('Succeeded','Failed','Denied')),
    CONSTRAINT "FK_AuditEvents_Users_ActorUserId" FOREIGN KEY ("ActorUserId") REFERENCES _identity_kyc_reference."Users" ("Id")
);

CREATE TABLE _identity_kyc_reference."AuthSessions" (
    "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "UserId" uuid NOT NULL,
    "FamilyId" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "RefreshTokenHash" bytea NOT NULL,
    "DeviceName" character varying(200),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "ExpiresAt" timestamp with time zone NOT NULL,
    "RevokedAt" timestamp with time zone,
    "RevocationReason" character varying(100),
    CONSTRAINT "PK_AuthSessions" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_AuthSessions_1" CHECK (octet_length("RefreshTokenHash") = 32),
    CONSTRAINT "CK_AuthSessions_2" CHECK ("ExpiresAt" > "CreatedAt"),
    CONSTRAINT "FK_AuthSessions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES _identity_kyc_reference."Users" ("Id")
);

CREATE TABLE _identity_kyc_reference."KycApplications" (
    "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "RegistrationApplicationId" uuid NOT NULL,
    "Status" character varying(20) NOT NULL DEFAULT 'Draft',
    "SubmittedAt" timestamp with time zone,
    "ReviewedAt" timestamp with time zone,
    "ReviewerUserId" uuid,
    "ReviewerReference" character varying(200),
    "RejectionCode" character varying(100),
    "ReviewNote" character varying(1000),
    "Version" bigint NOT NULL DEFAULT 1,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_KycApplications" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_KycApplications_1" CHECK ("Status" IN ('Draft','Submitted','UnderReview','Approved','Rejected')),
    CONSTRAINT "CK_KycApplications_2" CHECK ("Status" = 'Draft' OR "SubmittedAt" IS NOT NULL),
    CONSTRAINT "CK_KycApplications_3" CHECK ("Status" NOT IN ('Approved','Rejected') OR ("ReviewedAt" IS NOT NULL AND "ReviewerReference" IS NOT NULL AND length(btrim("ReviewerReference")) > 0)),
    CONSTRAINT "CK_KycApplications_4" CHECK ("Status" <> 'Rejected' OR ("RejectionCode" IS NOT NULL AND length(btrim("RejectionCode")) > 0)),
    CONSTRAINT "CK_KycApplications_5" CHECK ("ReviewedAt" IS NULL OR ("SubmittedAt" IS NOT NULL AND "ReviewedAt" >= "SubmittedAt")),
    CONSTRAINT "CK_KycApplications_6" CHECK ("Version" > 0),
    CONSTRAINT "FK_KycApplications_RegistrationApplications_RegistrationApplic~" FOREIGN KEY ("RegistrationApplicationId") REFERENCES _identity_kyc_reference."RegistrationApplications" ("Id"),
    CONSTRAINT "FK_KycApplications_Users_ReviewerUserId" FOREIGN KEY ("ReviewerUserId") REFERENCES _identity_kyc_reference."Users" ("Id")
);

CREATE TABLE _identity_kyc_reference."UserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_UserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserClaims_Users_UserId" FOREIGN KEY ("UserId") REFERENCES _identity_kyc_reference."Users" ("Id")
);

CREATE TABLE _identity_kyc_reference."UserLogins" (
    "LoginProvider" character varying(128) NOT NULL,
    "ProviderKey" character varying(128) NOT NULL,
    "ProviderDisplayName" text,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_UserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_UserLogins_Users_UserId" FOREIGN KEY ("UserId") REFERENCES _identity_kyc_reference."Users" ("Id")
);

CREATE TABLE _identity_kyc_reference."UserRoles" (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_UserRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES _identity_kyc_reference."Roles" ("Id"),
    CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES _identity_kyc_reference."Users" ("Id")
);

CREATE TABLE _identity_kyc_reference."UserTokens" (
    "UserId" uuid NOT NULL,
    "LoginProvider" character varying(128) NOT NULL,
    "Name" character varying(128) NOT NULL,
    "Value" text,
    CONSTRAINT "PK_UserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_UserTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES _identity_kyc_reference."Users" ("Id")
);

CREATE TABLE _identity_kyc_reference."VerificationChallenges" (
    "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "RegistrationApplicationId" uuid,
    "UserId" uuid,
    "Purpose" character varying(30) NOT NULL,
    "Destination" character varying(256) NOT NULL,
    "CodeHmac" bytea NOT NULL,
    "HmacKeyId" character varying(100) NOT NULL,
    "AttemptCount" integer NOT NULL DEFAULT 0,
    "MaxAttempts" integer NOT NULL DEFAULT 5,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "ExpiresAt" timestamp with time zone NOT NULL,
    "ConsumedAt" timestamp with time zone,
    "RevokedAt" timestamp with time zone,
    CONSTRAINT "PK_VerificationChallenges" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_VerificationChallenges_1" CHECK (("RegistrationApplicationId" IS NOT NULL) <> ("UserId" IS NOT NULL)),
    CONSTRAINT "CK_VerificationChallenges_2" CHECK (("RegistrationApplicationId" IS NOT NULL AND "Purpose" = 'RegistrationPhone') OR ("UserId" IS NOT NULL AND "Purpose" IN ('PasswordReset','VerifyEmail'))),
    CONSTRAINT "CK_VerificationChallenges_3" CHECK (octet_length("CodeHmac") = 32),
    CONSTRAINT "CK_VerificationChallenges_4" CHECK ("MaxAttempts" > 0 AND "AttemptCount" BETWEEN 0 AND "MaxAttempts"),
    CONSTRAINT "CK_VerificationChallenges_5" CHECK ("ExpiresAt" > "CreatedAt"),
    CONSTRAINT "FK_VerificationChallenges_RegistrationApplications_Registratio~" FOREIGN KEY ("RegistrationApplicationId") REFERENCES _identity_kyc_reference."RegistrationApplications" ("Id"),
    CONSTRAINT "FK_VerificationChallenges_Users_UserId" FOREIGN KEY ("UserId") REFERENCES _identity_kyc_reference."Users" ("Id")
);

CREATE TABLE _identity_kyc_reference."KycDocuments" (
    "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "ApplicationId" uuid NOT NULL,
    "DocumentType" character varying(20) NOT NULL,
    "StorageKey" text NOT NULL,
    "ContentType" character varying(100) NOT NULL,
    "SizeBytes" bigint NOT NULL,
    "UploadedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "DeleteAfter" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_KycDocuments" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_KycDocuments_1" CHECK ("DocumentType" IN ('IdentityFront','IdentityBack','Selfie')),
    CONSTRAINT "CK_KycDocuments_2" CHECK (length(btrim("StorageKey")) > 0),
    CONSTRAINT "CK_KycDocuments_3" CHECK ("SizeBytes" > 0),
    CONSTRAINT "CK_KycDocuments_4" CHECK ("DeleteAfter" IS NULL OR "DeleteAfter" > "UploadedAt"),
    CONSTRAINT "CK_KycDocuments_5" CHECK ("DeletedAt" IS NULL OR "DeletedAt" >= "UploadedAt"),
    CONSTRAINT "FK_KycDocuments_KycApplications_ApplicationId" FOREIGN KEY ("ApplicationId") REFERENCES _identity_kyc_reference."KycApplications" ("Id")
);

CREATE TABLE _identity_kyc_reference."KycIdentityDetails" (
    "ApplicationId" uuid NOT NULL,
    "FullName" character varying(150) NOT NULL,
    "DateOfBirth" date NOT NULL,
    "IdentityNumberEncrypted" bytea NOT NULL,
    "EncryptionKeyId" character varying(100) NOT NULL,
    "IdentityNumberHmac" bytea NOT NULL,
    "HmacKeyId" character varying(100) NOT NULL,
    "IssuedOn" date,
    "ExpiresOn" date,
    CONSTRAINT "PK_KycIdentityDetails" PRIMARY KEY ("ApplicationId"),
    CONSTRAINT "CK_KycIdentityDetails_1" CHECK (length(btrim("FullName")) > 0),
    CONSTRAINT "CK_KycIdentityDetails_2" CHECK (octet_length("IdentityNumberEncrypted") > 0),
    CONSTRAINT "CK_KycIdentityDetails_3" CHECK (octet_length("IdentityNumberHmac") = 32),
    CONSTRAINT "CK_KycIdentityDetails_4" CHECK ("IssuedOn" IS NULL OR "IssuedOn" >= "DateOfBirth"),
    CONSTRAINT "CK_KycIdentityDetails_5" CHECK ("ExpiresOn" IS NULL OR "IssuedOn" IS NULL OR "ExpiresOn" >= "IssuedOn"),
    CONSTRAINT "FK_KycIdentityDetails_KycApplications_ApplicationId" FOREIGN KEY ("ApplicationId") REFERENCES _identity_kyc_reference."KycApplications" ("Id")
);

CREATE INDEX "IX_Audit_Actor" ON _identity_kyc_reference."AuditEvents" ("ActorUserId", "OccurredAt");

CREATE INDEX "IX_Audit_Target" ON _identity_kyc_reference."AuditEvents" ("TargetType", "TargetId", "OccurredAt");

CREATE UNIQUE INDEX "AuthSessions_RefreshTokenHash_key" ON _identity_kyc_reference."AuthSessions" ("RefreshTokenHash");

CREATE INDEX "IX_AuthSessions_Family" ON _identity_kyc_reference."AuthSessions" ("FamilyId");

CREATE INDEX "IX_AuthSessions_User" ON _identity_kyc_reference."AuthSessions" ("UserId");

CREATE INDEX "IX_Kyc_Reviewer" ON _identity_kyc_reference."KycApplications" ("ReviewerUserId");

CREATE INDEX "IX_Kyc_ReviewQueue" ON _identity_kyc_reference."KycApplications" ("Status", "SubmittedAt", "Id");

CREATE UNIQUE INDEX "UX_Kyc_ActiveApplication" ON _identity_kyc_reference."KycApplications" ("RegistrationApplicationId") WHERE "Status" IN ('Draft','Submitted','UnderReview','Approved');

CREATE UNIQUE INDEX "KycDocuments_ApplicationId_DocumentType_key" ON _identity_kyc_reference."KycDocuments" ("ApplicationId", "DocumentType");

CREATE UNIQUE INDEX "KycDocuments_StorageKey_key" ON _identity_kyc_reference."KycDocuments" ("StorageKey");

CREATE INDEX "IX_KycIdentity_IdentityNumber" ON _identity_kyc_reference."KycIdentityDetails" ("HmacKeyId", "IdentityNumberHmac");

CREATE UNIQUE INDEX "UX_Registration_ActivePhone" ON _identity_kyc_reference."RegistrationApplications" ("PhoneNumber") WHERE "Status" = 'InProgress';

CREATE INDEX "IX_RegistrationSessions_Application" ON _identity_kyc_reference."RegistrationSessions" ("RegistrationApplicationId");

CREATE UNIQUE INDEX "RegistrationSessions_TokenHash_key" ON _identity_kyc_reference."RegistrationSessions" ("TokenHash");

CREATE INDEX "IX_RoleClaims_RoleId" ON _identity_kyc_reference."RoleClaims" ("RoleId");

CREATE UNIQUE INDEX "Roles_NormalizedName_key" ON _identity_kyc_reference."Roles" ("NormalizedName");

CREATE INDEX "IX_UserClaims_UserId" ON _identity_kyc_reference."UserClaims" ("UserId");

CREATE INDEX "IX_UserLogins_UserId" ON _identity_kyc_reference."UserLogins" ("UserId");

CREATE INDEX "IX_UserRoles_RoleId" ON _identity_kyc_reference."UserRoles" ("RoleId");

CREATE UNIQUE INDEX "Users_PhoneNumber_key" ON _identity_kyc_reference."Users" ("PhoneNumber");

CREATE UNIQUE INDEX "Users_RegistrationApplicationId_key" ON _identity_kyc_reference."Users" ("RegistrationApplicationId");

CREATE UNIQUE INDEX "UX_Users_NormalizedEmail" ON _identity_kyc_reference."Users" ("NormalizedEmail") WHERE "NormalizedEmail" IS NOT NULL;

CREATE UNIQUE INDEX "UX_Users_NormalizedUserName" ON _identity_kyc_reference."Users" ("NormalizedUserName");

CREATE INDEX "IX_Challenges_Registration" ON _identity_kyc_reference."VerificationChallenges" ("RegistrationApplicationId", "CreatedAt" DESC);

CREATE INDEX "IX_Challenges_User" ON _identity_kyc_reference."VerificationChallenges" ("UserId", "CreatedAt" DESC);

CREATE FUNCTION _identity_kyc_reference."ValidateUserRegistration"()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
    registration_row _identity_kyc_reference."RegistrationApplications"%ROWTYPE;
    approved_kyc_id UUID;
    document_count INTEGER;
BEGIN
    SELECT * INTO registration_row
    FROM _identity_kyc_reference."RegistrationApplications"
    WHERE "Id" = NEW."RegistrationApplicationId" FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Registration application does not exist';
    END IF;
    IF registration_row."Status" <> 'InProgress' THEN
        RAISE EXCEPTION 'Registration application is not active';
    END IF;
    IF registration_row."ExpiresAt" <= CURRENT_TIMESTAMP THEN
        RAISE EXCEPTION 'Registration application has expired';
    END IF;
    IF registration_row."PhoneVerifiedAt" IS NULL THEN
        RAISE EXCEPTION 'Phone number has not been verified';
    END IF;
    IF NEW."PhoneNumber" <> registration_row."PhoneNumber"
       OR NOT NEW."PhoneNumberConfirmed" THEN
        RAISE EXCEPTION 'User phone does not match verified registration';
    END IF;
    SELECT "Id" INTO approved_kyc_id
    FROM _identity_kyc_reference."KycApplications"
    WHERE "RegistrationApplicationId" = registration_row."Id"
      AND "Status" = 'Approved' FOR UPDATE;
    IF approved_kyc_id IS NULL THEN
        RAISE EXCEPTION 'Approved KYC is required';
    END IF;
    PERFORM 1 FROM _identity_kyc_reference."KycIdentityDetails"
    WHERE "ApplicationId" = approved_kyc_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'KYC identity details are missing';
    END IF;
    SELECT COUNT(*) INTO document_count FROM _identity_kyc_reference."KycDocuments"
    WHERE "ApplicationId" = approved_kyc_id AND "DeletedAt" IS NULL;
    IF document_count <> 3 THEN
        RAISE EXCEPTION 'CCCD front, CCCD back and selfie are required';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER "TR_Users_ValidateRegistration"
BEFORE INSERT ON _identity_kyc_reference."Users"
FOR EACH ROW EXECUTE FUNCTION _identity_kyc_reference."ValidateUserRegistration"();

CREATE FUNCTION _identity_kyc_reference."CompleteUserRegistration"()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    UPDATE _identity_kyc_reference."RegistrationApplications"
    SET "Status" = 'Completed',
        "CompletedAt" = CURRENT_TIMESTAMP,
        "UpdatedAt" = CURRENT_TIMESTAMP
    WHERE "Id" = NEW."RegistrationApplicationId";
    RETURN NEW;
END;
$$;
CREATE TRIGGER "TR_Users_CompleteRegistration"
AFTER INSERT ON _identity_kyc_reference."Users"
FOR EACH ROW EXECUTE FUNCTION _identity_kyc_reference."CompleteUserRegistration"();

CREATE FUNCTION _identity_kyc_reference."ProtectUserRegistrationLink"()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    IF NEW."RegistrationApplicationId"
       IS DISTINCT FROM OLD."RegistrationApplicationId" THEN
        RAISE EXCEPTION 'User registration link cannot be changed';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER "TR_Users_ProtectRegistrationLink"
BEFORE UPDATE OF "RegistrationApplicationId" ON _identity_kyc_reference."Users"
FOR EACH ROW EXECUTE FUNCTION _identity_kyc_reference."ProtectUserRegistrationLink"();

INSERT INTO _identity_kyc_reference."Roles" ("Name", "NormalizedName", "ConcurrencyStamp")
VALUES ('User', 'USER', gen_random_uuid()::TEXT),
       ('KycReviewer', 'KYCREVIEWER', gen_random_uuid()::TEXT),
       ('Admin', 'ADMIN', gen_random_uuid()::TEXT)
ON CONFLICT ("NormalizedName") DO NOTHING;


-- Executed after the reference schema has been created inside this transaction.
SET LOCAL search_path = pg_catalog;

DO $baseline$
DECLARE
    item RECORD;
    actual_name TEXT;
    actual_constraint TEXT;
    expected_signature TEXT;
    reparsed_signature TEXT;
    matches INTEGER;
BEGIN
    -- Lock only the 15 application tables; no row data is changed.
    FOR item IN
        SELECT tablename FROM pg_tables
        WHERE schemaname = '_identity_kyc_reference'
        ORDER BY tablename
    LOOP
        EXECUTE format('LOCK TABLE public.%I IN ACCESS EXCLUSIVE MODE NOWAIT', item.tablename);
    END LOOP;

    IF EXISTS (
        WITH columns AS (
            SELECT n.nspname, c.relname, a.attname,
                   format_type(a.atttypid, a.atttypmod) AS data_type,
                   a.attnotnull, a.attidentity, a.attgenerated,
                   pg_get_expr(d.adbin, d.adrelid) AS default_value
            FROM pg_attribute a
            JOIN pg_class c ON c.oid = a.attrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            LEFT JOIN pg_attrdef d ON d.adrelid = c.oid AND d.adnum = a.attnum
            WHERE a.attnum > 0 AND NOT a.attisdropped AND c.relkind = 'r'
              AND n.nspname IN ('public', '_identity_kyc_reference')
              AND c.relname IN (
                  SELECT tablename FROM pg_tables
                  WHERE schemaname = '_identity_kyc_reference'
              )
        )
        SELECT 1
        FROM (SELECT * FROM columns WHERE nspname = '_identity_kyc_reference') expected
        FULL JOIN (SELECT * FROM columns WHERE nspname = 'public') actual
            USING (relname, attname)
        WHERE ROW(expected.data_type, expected.attnotnull, expected.attidentity,
                  expected.attgenerated, expected.default_value)
              IS DISTINCT FROM
              ROW(actual.data_type, actual.attnotnull, actual.attidentity,
                  actual.attgenerated, actual.default_value)
           OR expected.nspname IS NULL OR actual.nspname IS NULL
    ) THEN
        RAISE EXCEPTION 'Baseline stopped: column types, nullability, defaults or identity settings differ';
    END IF;

    -- Match primary keys, foreign keys and CHECK constraints by definition.
    -- Names from the handwritten SQL are normalized to the EF migration names.
    FOR item IN
        SELECT c.relname, k.conname, k.contype,
               replace(pg_get_constraintdef(k.oid), '_identity_kyc_reference.', 'public.') AS definition
        FROM pg_constraint k
        JOIN pg_class c ON c.oid = k.conrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = '_identity_kyc_reference' AND k.contype IN ('p', 'f', 'c')
        ORDER BY k.contype, c.relname, k.conname
    LOOP
        reparsed_signature := item.definition;
        IF item.contype = 'c' THEN
            -- PostgreSQL may canonicalize text-array casts after a dump/restore.
            -- Reparse the same CHECK on the scratch table to accept that form too.
            EXECUTE format('ALTER TABLE _identity_kyc_reference.%I DROP CONSTRAINT %I',
                           item.relname, item.conname);
            EXECUTE format('ALTER TABLE _identity_kyc_reference.%I ADD CONSTRAINT %I %s',
                           item.relname, item.conname, item.definition);
            SELECT pg_get_constraintdef(k.oid) INTO reparsed_signature
            FROM pg_constraint k
            WHERE k.conrelid = format('_identity_kyc_reference.%I', item.relname)::regclass
              AND k.conname = item.conname;
        END IF;
        SELECT count(*), min(k.conname::TEXT)
        INTO matches, actual_name
        FROM pg_constraint k
        WHERE k.conrelid = format('public.%I', item.relname)::regclass
          AND k.contype = item.contype
          AND pg_get_constraintdef(k.oid) IN (item.definition, reparsed_signature)
          AND k.convalidated;
        IF matches <> 1 THEN
            RAISE EXCEPTION 'Baseline stopped: constraint mismatch on %.%', item.relname, item.conname;
        END IF;
        IF actual_name <> item.conname THEN
            EXECUTE format('ALTER TABLE public.%I RENAME CONSTRAINT %I TO %I',
                           item.relname, actual_name, item.conname);
        END IF;
    END LOOP;

    IF (
        SELECT count(*) FROM pg_constraint k JOIN pg_class c ON c.oid = k.conrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'public' AND k.contype IN ('p', 'f', 'c', 'x')
          AND c.relname IN (SELECT tablename FROM pg_tables WHERE schemaname = '_identity_kyc_reference')
    ) <> (
        SELECT count(*) FROM pg_constraint k JOIN pg_class c ON c.oid = k.conrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = '_identity_kyc_reference' AND k.contype IN ('p', 'f', 'c', 'x')
    ) THEN
        RAISE EXCEPTION 'Baseline stopped: unexpected constraints';
    END IF;

    -- EF models these uniqueness rules as indexes. Convert equivalent UNIQUE
    -- constraints into unique indexes while holding the table locks.
    -- No CASCADE: unexpected dependents cause the entire transaction to fail.
    FOR item IN
        SELECT c.relname, idx.relname AS index_name, i.indisunique,
               substring(pg_get_indexdef(i.indexrelid) FROM ' USING .*') AS signature,
               replace(pg_get_indexdef(i.indexrelid), '_identity_kyc_reference.', 'public.') AS definition
        FROM pg_index i
        JOIN pg_class c ON c.oid = i.indrelid
        JOIN pg_class idx ON idx.oid = i.indexrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = '_identity_kyc_reference' AND NOT i.indisprimary
    LOOP
        EXECUTE format('DROP INDEX _identity_kyc_reference.%I', item.index_name);
        EXECUTE replace(item.definition, 'public.', '_identity_kyc_reference.');
        SELECT substring(pg_get_indexdef(format('_identity_kyc_reference.%I', item.index_name)::regclass)
                         FROM ' USING .*') INTO reparsed_signature;
        SELECT count(*), min(idx.relname::TEXT)
        INTO matches, actual_name
        FROM pg_index i JOIN pg_class idx ON idx.oid = i.indexrelid
        WHERE i.indrelid = format('public.%I', item.relname)::regclass
          AND NOT i.indisprimary AND i.indisunique = item.indisunique
          AND i.indisvalid AND i.indisready
          AND substring(pg_get_indexdef(i.indexrelid) FROM ' USING .*')
              IN (item.signature, reparsed_signature);
        IF matches <> 1 THEN
            RAISE EXCEPTION 'Baseline stopped: index mismatch on %.%', item.relname, item.index_name;
        END IF;

        SELECT k.conname INTO actual_constraint
        FROM pg_constraint k
        WHERE k.conindid = format('public.%I', actual_name)::regclass AND k.contype = 'u';
        IF actual_constraint IS NOT NULL THEN
            EXECUTE format('ALTER TABLE public.%I DROP CONSTRAINT %I', item.relname, actual_constraint);
            EXECUTE item.definition;
        ELSIF actual_name <> item.index_name THEN
            EXECUTE format('ALTER INDEX public.%I RENAME TO %I', actual_name, item.index_name);
        END IF;
    END LOOP;

    IF (
        SELECT count(*) FROM pg_index i JOIN pg_class c ON c.oid = i.indrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'public'
          AND c.relname IN (SELECT tablename FROM pg_tables WHERE schemaname = '_identity_kyc_reference')
    ) <> (
        SELECT count(*) FROM pg_index i JOIN pg_class c ON c.oid = i.indrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = '_identity_kyc_reference'
    ) THEN
        RAISE EXCEPTION 'Baseline stopped: unexpected indexes';
    END IF;

    FOR item IN
        SELECT replace(pg_get_triggerdef(t.oid), '_identity_kyc_reference.', 'public.') AS definition
        FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = '_identity_kyc_reference' AND NOT t.tgisinternal
    LOOP
        IF NOT EXISTS (
            SELECT 1 FROM pg_trigger t
            WHERE t.tgrelid = 'public."Users"'::regclass AND NOT t.tgisinternal
              AND t.tgenabled = 'O' AND pg_get_triggerdef(t.oid) = item.definition
        ) THEN
            RAISE EXCEPTION 'Baseline stopped: registration trigger mismatch';
        END IF;
    END LOOP;
    IF (SELECT count(*) FROM pg_trigger
        WHERE tgrelid = 'public."Users"'::regclass AND NOT tgisinternal) <> 3 THEN
        RAISE EXCEPTION 'Baseline stopped: unexpected user triggers';
    END IF;

    -- Install the reviewed migration function bodies without changing table data.
    FOR item IN
        SELECT replace(pg_get_functiondef(p.oid), '_identity_kyc_reference.', 'public.') AS definition
        FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
        WHERE n.nspname = '_identity_kyc_reference'
    LOOP
        EXECUTE item.definition;
    END LOOP;

    IF (SELECT count(*) FROM public."Roles"
        WHERE ("Name", "NormalizedName") IN
            (('User','USER'), ('KycReviewer','KYCREVIEWER'), ('Admin','ADMIN'))) <> 3 THEN
        RAISE EXCEPTION 'Baseline stopped: required roles are missing';
    END IF;
END;
$baseline$;

-- Only the scratch schema created above is removed; public tables remain.
DROP SCHEMA _identity_kyc_reference CASCADE;
INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260917023949_InitialIdentityKyc', '10.0.4');

COMMIT;


