CREATE TABLE IF NOT EXISTS public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE public."RegistrationApplications" (
    "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "PhoneNumber" character varying(20) NOT NULL,
    "PhoneVerifiedAt" timestamp with time zone,
    "DisplayName" character varying(150),
    "Status" character varying(20) NOT NULL DEFAULT 'InProgress',
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "ExpiresAt" timestamp with time zone NOT NULL,
    "CompletedAt" timestamp with time zone,
    CONSTRAINT "PK_RegistrationApplications" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_RegistrationApplications_1" CHECK ("PhoneNumber" ~ '^\+[1-9][0-9]{7,14}$'),
    CONSTRAINT "CK_RegistrationApplications_2" CHECK ("Status" IN ('InProgress','Completed','Expired','Cancelled')),
    CONSTRAINT "CK_RegistrationApplications_3" CHECK ("ExpiresAt" > "CreatedAt"),
    CONSTRAINT "CK_RegistrationApplications_4" CHECK (("Status" = 'Completed') = ("CompletedAt" IS NOT NULL))
);

CREATE TABLE public."Roles" (
    "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "Name" character varying(256) NOT NULL,
    "NormalizedName" character varying(256) NOT NULL,
    "ConcurrencyStamp" text NOT NULL,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

CREATE TABLE public."RegistrationSessions" (
    "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "RegistrationApplicationId" uuid NOT NULL,
    "TokenHash" bytea NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "ExpiresAt" timestamp with time zone NOT NULL,
    "RevokedAt" timestamp with time zone,
    CONSTRAINT "PK_RegistrationSessions" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_RegistrationSessions_1" CHECK (octet_length("TokenHash") = 32),
    CONSTRAINT "CK_RegistrationSessions_2" CHECK ("ExpiresAt" > "CreatedAt"),
    CONSTRAINT "FK_RegistrationSessions_RegistrationApplications_RegistrationA~" FOREIGN KEY ("RegistrationApplicationId") REFERENCES public."RegistrationApplications" ("Id")
);

CREATE TABLE public."Users" (
    "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "RegistrationApplicationId" uuid NOT NULL,
    "DisplayName" character varying(150) NOT NULL,
    "AccountStatus" character varying(20) NOT NULL DEFAULT 'Active',
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UserName" character varying(256) NOT NULL,
    "NormalizedUserName" character varying(256) NOT NULL,
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL DEFAULT FALSE,
    "PasswordHash" text NOT NULL,
    "SecurityStamp" text NOT NULL,
    "ConcurrencyStamp" text NOT NULL,
    "PhoneNumber" character varying(20) NOT NULL,
    "PhoneNumberConfirmed" boolean NOT NULL DEFAULT TRUE,
    "TwoFactorEnabled" boolean NOT NULL DEFAULT FALSE,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL DEFAULT TRUE,
    "AccessFailedCount" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_Users_Failures" CHECK ("AccessFailedCount" >= 0),
    CONSTRAINT "CK_Users_Name" CHECK (length(btrim("DisplayName")) > 0),
    CONSTRAINT "CK_Users_Password" CHECK (length(btrim("PasswordHash")) > 0),
    CONSTRAINT "CK_Users_Phone" CHECK ("PhoneNumber" ~ '^\+[1-9][0-9]{7,14}$'),
    CONSTRAINT "CK_Users_Status" CHECK ("AccountStatus" IN ('Active','Suspended','Disabled')),
    CONSTRAINT "FK_Users_RegistrationApplications_RegistrationApplicationId" FOREIGN KEY ("RegistrationApplicationId") REFERENCES public."RegistrationApplications" ("Id")
);

CREATE TABLE public."RoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_RoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RoleClaims_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."Roles" ("Id")
);

CREATE TABLE public."AuditEvents" (
    "Id" bigint GENERATED ALWAYS AS IDENTITY,
    "ActorUserId" uuid,
    "ActorReference" character varying(200),
    "Action" character varying(100) NOT NULL,
    "TargetType" character varying(100) NOT NULL,
    "TargetId" uuid NOT NULL,
    "Outcome" character varying(20) NOT NULL,
    "TraceId" character varying(100),
    "OccurredAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_AuditEvents" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_AuditEvents_1" CHECK ("Outcome" IN ('Succeeded','Failed','Denied')),
    CONSTRAINT "FK_AuditEvents_Users_ActorUserId" FOREIGN KEY ("ActorUserId") REFERENCES public."Users" ("Id")
);

CREATE TABLE public."AuthSessions" (
    "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "UserId" uuid NOT NULL,
    "FamilyId" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "RefreshTokenHash" bytea NOT NULL,
    "DeviceName" character varying(200),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "ExpiresAt" timestamp with time zone NOT NULL,
    "RevokedAt" timestamp with time zone,
    "RevocationReason" character varying(100),
    CONSTRAINT "PK_AuthSessions" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_AuthSessions_1" CHECK (octet_length("RefreshTokenHash") = 32),
    CONSTRAINT "CK_AuthSessions_2" CHECK ("ExpiresAt" > "CreatedAt"),
    CONSTRAINT "FK_AuthSessions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users" ("Id")
);

CREATE TABLE public."KycApplications" (
    "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "RegistrationApplicationId" uuid NOT NULL,
    "Status" character varying(20) NOT NULL DEFAULT 'Draft',
    "SubmittedAt" timestamp with time zone,
    "ReviewedAt" timestamp with time zone,
    "ReviewerUserId" uuid,
    "ReviewerReference" character varying(200),
    "RejectionCode" character varying(100),
    "ReviewNote" character varying(1000),
    "Version" bigint NOT NULL DEFAULT 1,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_KycApplications" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_KycApplications_1" CHECK ("Status" IN ('Draft','Submitted','UnderReview','Approved','Rejected')),
    CONSTRAINT "CK_KycApplications_2" CHECK ("Status" = 'Draft' OR "SubmittedAt" IS NOT NULL),
    CONSTRAINT "CK_KycApplications_3" CHECK ("Status" NOT IN ('Approved','Rejected') OR ("ReviewedAt" IS NOT NULL AND "ReviewerReference" IS NOT NULL AND length(btrim("ReviewerReference")) > 0)),
    CONSTRAINT "CK_KycApplications_4" CHECK ("Status" <> 'Rejected' OR ("RejectionCode" IS NOT NULL AND length(btrim("RejectionCode")) > 0)),
    CONSTRAINT "CK_KycApplications_5" CHECK ("ReviewedAt" IS NULL OR ("SubmittedAt" IS NOT NULL AND "ReviewedAt" >= "SubmittedAt")),
    CONSTRAINT "CK_KycApplications_6" CHECK ("Version" > 0),
    CONSTRAINT "FK_KycApplications_RegistrationApplications_RegistrationApplic~" FOREIGN KEY ("RegistrationApplicationId") REFERENCES public."RegistrationApplications" ("Id"),
    CONSTRAINT "FK_KycApplications_Users_ReviewerUserId" FOREIGN KEY ("ReviewerUserId") REFERENCES public."Users" ("Id")
);

CREATE TABLE public."UserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_UserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserClaims_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users" ("Id")
);

CREATE TABLE public."UserLogins" (
    "LoginProvider" character varying(128) NOT NULL,
    "ProviderKey" character varying(128) NOT NULL,
    "ProviderDisplayName" text,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_UserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_UserLogins_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users" ("Id")
);

CREATE TABLE public."UserRoles" (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_UserRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."Roles" ("Id"),
    CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users" ("Id")
);

CREATE TABLE public."UserTokens" (
    "UserId" uuid NOT NULL,
    "LoginProvider" character varying(128) NOT NULL,
    "Name" character varying(128) NOT NULL,
    "Value" text,
    CONSTRAINT "PK_UserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_UserTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users" ("Id")
);

CREATE TABLE public."VerificationChallenges" (
    "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "RegistrationApplicationId" uuid,
    "UserId" uuid,
    "Purpose" character varying(30) NOT NULL,
    "Destination" character varying(256) NOT NULL,
    "CodeHmac" bytea NOT NULL,
    "HmacKeyId" character varying(100) NOT NULL,
    "AttemptCount" integer NOT NULL DEFAULT 0,
    "MaxAttempts" integer NOT NULL DEFAULT 5,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "ExpiresAt" timestamp with time zone NOT NULL,
    "ConsumedAt" timestamp with time zone,
    "RevokedAt" timestamp with time zone,
    CONSTRAINT "PK_VerificationChallenges" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_VerificationChallenges_1" CHECK (("RegistrationApplicationId" IS NOT NULL) <> ("UserId" IS NOT NULL)),
    CONSTRAINT "CK_VerificationChallenges_2" CHECK (("RegistrationApplicationId" IS NOT NULL AND "Purpose" = 'RegistrationPhone') OR ("UserId" IS NOT NULL AND "Purpose" IN ('PasswordReset','VerifyEmail'))),
    CONSTRAINT "CK_VerificationChallenges_3" CHECK (octet_length("CodeHmac") = 32),
    CONSTRAINT "CK_VerificationChallenges_4" CHECK ("MaxAttempts" > 0 AND "AttemptCount" BETWEEN 0 AND "MaxAttempts"),
    CONSTRAINT "CK_VerificationChallenges_5" CHECK ("ExpiresAt" > "CreatedAt"),
    CONSTRAINT "FK_VerificationChallenges_RegistrationApplications_Registratio~" FOREIGN KEY ("RegistrationApplicationId") REFERENCES public."RegistrationApplications" ("Id"),
    CONSTRAINT "FK_VerificationChallenges_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users" ("Id")
);

CREATE TABLE public."KycDocuments" (
    "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "ApplicationId" uuid NOT NULL,
    "DocumentType" character varying(20) NOT NULL,
    "StorageKey" text NOT NULL,
    "ContentType" character varying(100) NOT NULL,
    "SizeBytes" bigint NOT NULL,
    "UploadedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "DeleteAfter" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_KycDocuments" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_KycDocuments_1" CHECK ("DocumentType" IN ('IdentityFront','IdentityBack','Selfie')),
    CONSTRAINT "CK_KycDocuments_2" CHECK (length(btrim("StorageKey")) > 0),
    CONSTRAINT "CK_KycDocuments_3" CHECK ("SizeBytes" > 0),
    CONSTRAINT "CK_KycDocuments_4" CHECK ("DeleteAfter" IS NULL OR "DeleteAfter" > "UploadedAt"),
    CONSTRAINT "CK_KycDocuments_5" CHECK ("DeletedAt" IS NULL OR "DeletedAt" >= "UploadedAt"),
    CONSTRAINT "FK_KycDocuments_KycApplications_ApplicationId" FOREIGN KEY ("ApplicationId") REFERENCES public."KycApplications" ("Id")
);

CREATE TABLE public."KycIdentityDetails" (
    "ApplicationId" uuid NOT NULL,
    "FullName" character varying(150) NOT NULL,
    "DateOfBirth" date NOT NULL,
    "IdentityNumberEncrypted" bytea NOT NULL,
    "EncryptionKeyId" character varying(100) NOT NULL,
    "IdentityNumberHmac" bytea NOT NULL,
    "HmacKeyId" character varying(100) NOT NULL,
    "IssuedOn" date,
    "ExpiresOn" date,
    CONSTRAINT "PK_KycIdentityDetails" PRIMARY KEY ("ApplicationId"),
    CONSTRAINT "CK_KycIdentityDetails_1" CHECK (length(btrim("FullName")) > 0),
    CONSTRAINT "CK_KycIdentityDetails_2" CHECK (octet_length("IdentityNumberEncrypted") > 0),
    CONSTRAINT "CK_KycIdentityDetails_3" CHECK (octet_length("IdentityNumberHmac") = 32),
    CONSTRAINT "CK_KycIdentityDetails_4" CHECK ("IssuedOn" IS NULL OR "IssuedOn" >= "DateOfBirth"),
    CONSTRAINT "CK_KycIdentityDetails_5" CHECK ("ExpiresOn" IS NULL OR "IssuedOn" IS NULL OR "ExpiresOn" >= "IssuedOn"),
    CONSTRAINT "FK_KycIdentityDetails_KycApplications_ApplicationId" FOREIGN KEY ("ApplicationId") REFERENCES public."KycApplications" ("Id")
);

CREATE INDEX "IX_Audit_Actor" ON public."AuditEvents" ("ActorUserId", "OccurredAt");

CREATE INDEX "IX_Audit_Target" ON public."AuditEvents" ("TargetType", "TargetId", "OccurredAt");

CREATE UNIQUE INDEX "AuthSessions_RefreshTokenHash_key" ON public."AuthSessions" ("RefreshTokenHash");

CREATE INDEX "IX_AuthSessions_Family" ON public."AuthSessions" ("FamilyId");

CREATE INDEX "IX_AuthSessions_User" ON public."AuthSessions" ("UserId");

CREATE INDEX "IX_Kyc_Reviewer" ON public."KycApplications" ("ReviewerUserId");

CREATE INDEX "IX_Kyc_ReviewQueue" ON public."KycApplications" ("Status", "SubmittedAt", "Id");

CREATE UNIQUE INDEX "UX_Kyc_ActiveApplication" ON public."KycApplications" ("RegistrationApplicationId") WHERE "Status" IN ('Draft','Submitted','UnderReview','Approved');

CREATE UNIQUE INDEX "KycDocuments_ApplicationId_DocumentType_key" ON public."KycDocuments" ("ApplicationId", "DocumentType");

CREATE UNIQUE INDEX "KycDocuments_StorageKey_key" ON public."KycDocuments" ("StorageKey");

CREATE INDEX "IX_KycIdentity_IdentityNumber" ON public."KycIdentityDetails" ("HmacKeyId", "IdentityNumberHmac");

CREATE UNIQUE INDEX "UX_Registration_ActivePhone" ON public."RegistrationApplications" ("PhoneNumber") WHERE "Status" = 'InProgress';

CREATE INDEX "IX_RegistrationSessions_Application" ON public."RegistrationSessions" ("RegistrationApplicationId");

CREATE UNIQUE INDEX "RegistrationSessions_TokenHash_key" ON public."RegistrationSessions" ("TokenHash");

CREATE INDEX "IX_RoleClaims_RoleId" ON public."RoleClaims" ("RoleId");

CREATE UNIQUE INDEX "Roles_NormalizedName_key" ON public."Roles" ("NormalizedName");

CREATE INDEX "IX_UserClaims_UserId" ON public."UserClaims" ("UserId");

CREATE INDEX "IX_UserLogins_UserId" ON public."UserLogins" ("UserId");

CREATE INDEX "IX_UserRoles_RoleId" ON public."UserRoles" ("RoleId");

CREATE UNIQUE INDEX "Users_PhoneNumber_key" ON public."Users" ("PhoneNumber");

CREATE UNIQUE INDEX "Users_RegistrationApplicationId_key" ON public."Users" ("RegistrationApplicationId");

CREATE UNIQUE INDEX "UX_Users_NormalizedEmail" ON public."Users" ("NormalizedEmail") WHERE "NormalizedEmail" IS NOT NULL;

CREATE UNIQUE INDEX "UX_Users_NormalizedUserName" ON public."Users" ("NormalizedUserName");

CREATE INDEX "IX_Challenges_Registration" ON public."VerificationChallenges" ("RegistrationApplicationId", "CreatedAt" DESC);

CREATE INDEX "IX_Challenges_User" ON public."VerificationChallenges" ("UserId", "CreatedAt" DESC);

CREATE FUNCTION public."ValidateUserRegistration"()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
    registration_row public."RegistrationApplications"%ROWTYPE;
    approved_kyc_id UUID;
    document_count INTEGER;
BEGIN
    SELECT * INTO registration_row
    FROM public."RegistrationApplications"
    WHERE "Id" = NEW."RegistrationApplicationId" FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Registration application does not exist';
    END IF;
    IF registration_row."Status" <> 'InProgress' THEN
        RAISE EXCEPTION 'Registration application is not active';
    END IF;
    IF registration_row."ExpiresAt" <= CURRENT_TIMESTAMP THEN
        RAISE EXCEPTION 'Registration application has expired';
    END IF;
    IF registration_row."PhoneVerifiedAt" IS NULL THEN
        RAISE EXCEPTION 'Phone number has not been verified';
    END IF;
    IF NEW."PhoneNumber" <> registration_row."PhoneNumber"
       OR NOT NEW."PhoneNumberConfirmed" THEN
        RAISE EXCEPTION 'User phone does not match verified registration';
    END IF;
    SELECT "Id" INTO approved_kyc_id
    FROM public."KycApplications"
    WHERE "RegistrationApplicationId" = registration_row."Id"
      AND "Status" = 'Approved' FOR UPDATE;
    IF approved_kyc_id IS NULL THEN
        RAISE EXCEPTION 'Approved KYC is required';
    END IF;
    PERFORM 1 FROM public."KycIdentityDetails"
    WHERE "ApplicationId" = approved_kyc_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'KYC identity details are missing';
    END IF;
    SELECT COUNT(*) INTO document_count FROM public."KycDocuments"
    WHERE "ApplicationId" = approved_kyc_id AND "DeletedAt" IS NULL;
    IF document_count <> 3 THEN
        RAISE EXCEPTION 'CCCD front, CCCD back and selfie are required';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER "TR_Users_ValidateRegistration"
BEFORE INSERT ON public."Users"
FOR EACH ROW EXECUTE FUNCTION public."ValidateUserRegistration"();

CREATE FUNCTION public."CompleteUserRegistration"()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    UPDATE public."RegistrationApplications"
    SET "Status" = 'Completed',
        "CompletedAt" = CURRENT_TIMESTAMP,
        "UpdatedAt" = CURRENT_TIMESTAMP
    WHERE "Id" = NEW."RegistrationApplicationId";
    RETURN NEW;
END;
$$;
CREATE TRIGGER "TR_Users_CompleteRegistration"
AFTER INSERT ON public."Users"
FOR EACH ROW EXECUTE FUNCTION public."CompleteUserRegistration"();

CREATE FUNCTION public."ProtectUserRegistrationLink"()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    IF NEW."RegistrationApplicationId"
       IS DISTINCT FROM OLD."RegistrationApplicationId" THEN
        RAISE EXCEPTION 'User registration link cannot be changed';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER "TR_Users_ProtectRegistrationLink"
BEFORE UPDATE OF "RegistrationApplicationId" ON public."Users"
FOR EACH ROW EXECUTE FUNCTION public."ProtectUserRegistrationLink"();

INSERT INTO public."Roles" ("Name", "NormalizedName", "ConcurrencyStamp")
VALUES ('User', 'USER', gen_random_uuid()::TEXT),
       ('KycReviewer', 'KYCREVIEWER', gen_random_uuid()::TEXT),
       ('Admin', 'ADMIN', gen_random_uuid()::TEXT)
ON CONFLICT ("NormalizedName") DO NOTHING;

INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260917023949_InitialIdentityKyc', '10.0.4');

COMMIT;

